### ISSUE TITLE
Consider using/supporting xdg base directory specification

### ISSUE THREAD

**Issue by rixx** [cherti/blinky#11]
Instead of defaulting to using ~/.blinky, it would be nice if blinky used $XDG_DATA_HOME/blinky (defaulting to ~/.local/share), and maybe even $XDG_CONFIG_HOME/blinky and $XDG_CACHE_HOME/blinky, if you're feeling fancy, as per the [XDG Base Directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by cherti** [comment]
Closed via bdbdfe1.
