### ISSUE TITLE
build fails on cmake-built packages when the user has CMAKE_GENERATOR set

### ISSUE THREAD

**Issue by pseyfert** [cherti/blinky#13]
there are cmake-built packages on AUR that build with

```sh
cmake path/to/source
make
```

rather than

```sh
cmake path/to/source
cmake --build .
```

the former fails if a user has CMAKE_GENERATOR set. So it seems preferential to make builds in a "clean" environment rather than a user's normal shell environment (for reproducible builds and such).

At the time of writing, it's not clear to me if maybe passing environment variables to the build might sometimes be desirable.

**Comment by cherti** [comment]
The question would be if it is beneficial to start makepkg with a clean environement while selectively moving things over from blinky's env, such as PATH and PKGEXT, or if whitelisting environement variables is too error prone and sisyphus work to be a valid solution for this. Given the latter, the problem must be left to the user, which is unsatisfying, but potentially documenting a way of unsetting certain variables explicitly might be a less cumbersome way of dealing with this issue for all participants involved.

**Comment by cherti** [comment]
Given that it is very unclear which environment variables are relevant to take and which are not, all of which is also highly dependent on the user's setup likely the most clean solution is to stick to `makepkg`'s behavior and take the full environment and to let the user make modifications and corrections of said environment within `makepkg.conf`, which is sourced by `makepkg` and therefore allows things like unsetting `CMAKE_GENERATOR`.
