### ISSUE TITLE
cache cleaning can't handle missing files in the cache

### ISSUE THREAD

**Issue by pseyfert** [cherti/blinky#14]
(already reported on irc, here for public record)

I recently removed single files from `~/.binky/cache` (old versions, package I decided to long term drop) simply by deleting the old files.
Running `blinky -Sc` later resulted in the following error:

```
Traceback (most recent call last):
  File "/home/pseyfert/.local/bin/blinky", line 332, in <module>
    clean_cache(keep_installed=True)
  File "/home/pseyfert/.local/bin/blinky", line 245, in clean_cache
    os.remove(f)
FileNotFoundError: [Errno 2] No such file or directory: 'openafs-modules-1.8.3-1-x86_64.pkg.tar.xz'
```

repeating `blinky -Sc` resulted in the same error **with a different file**.
Eventually (after getting one error per execution i.e. per manually deleted
file) the cache clean ran through without errors.

**Comment by cherti** [comment]
Fixed in 456aafddaf68cc281adf7f25aa59d6a32775fd47.
