### ISSUE TITLE
Unable to install git packages

### ISSUE THREAD

**Issue by paalsteek** [cherti/blinky#2]
For git packages the version in the PKGBUILD may not be up-to-date. In that case the package file is not found by blinky as it includes the version in the search pattern. This results in the following error message:

` !> Package file depot-tools-git-r5113.4d2e8bff-1-{x86_64,any}.pkg.tar.xz was not found in builddir, aborting this subtree
`
with the file depot-tools-git-r5119.88087bad-1-any.pkg.tar.xz being present within the build directory.

**Comment by cherti** [comment]
Fixed in  c8da84d.
